CREATE TABLE game (
    id BINARY(16) PRIMARY KEY,
    spy VARCHAR(32) NOT NULL,
    sniper VARCHAR(32) NOT NULL,
    result ENUM('MISSIONS_WIN','SPY_TIMEOUT','SPY_SHOT','CIVILIAN_SHOT','IN_PROGRESS') NOT NULL,
    winner ENUM('SPY','SNIPER'),
    map INT UNSIGNED NOT NULL,
    time DATETIME NOT NULL
);
